name: Run Auto Tests

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-echo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run test command
        run: echo "Tests passed"
